steps:
# We only need to update submodules in triggers. User must update submodule
# before local runs because .git is not present.
- name: 'alpine/git'
  entrypoint: sh
  args:
  - -c
  - |
    git submodule update --init || echo No git repository found
- id: 'common-flags'
  name: 'bash'
  args:
  - -c
  - |
    args=(${BUILD_ARGS//,/ })
    flags=(
      --cache=${_CACHE}
      --cache-ttl=${_CACHE_TTL}
      --use-new-run
      --build-arg=bazel_jobs=${_BAZEL_JOBS}
      --build-arg=python_version=${_PYTHON_VERSION}
      # TODO: use current version in setup.py
      --build-arg=torch_xla_version="1.14.dev$(date -u +%Y%m%d)"
      ${args[@]/#/--build-arg})
    echo ${flags[@]} | tee /docker/flags.txt
  volumes:
  - name: docker
    path: /docker
- id: 'build-wheels'
  name: 'gcr.io/kaniko-project/executor:debug'
  entrypoint: sh
  args:
  - -c
  - |
    /kaniko/executor \
      --dockerfile=docker/experimental/Dockerfile \
      --destination=${_IMAGE_URL}_artifacts \
      --tar-path=/image/artifacts-image.tar \
      --target=artifacts \
      $(cat /docker/flags.txt)
  timeout: 14400s
  volumes:
  - name: docker
    path: /docker
- id: 'import-artifacts'
  name: gcr.io/cloud-builders/docker
  args:
  - load
  - --input
  - /image/artifacts-image.tar
  volumes:
  - name: docker
    path: /docker
- id: 'copy-wheels'
  name: gcr.io/${PROJECT_ID}/experimental/xla:${_IMAGE_NAME}_artifacts
  entrypoint: bash
  args:
  - -c
  - |
    cp /pytorch/dist/*.whl /wheels
    cp /pytorch/xla/dist/*.whl /wheels
  volumes:
  - name: 'wheels'
    path: /wheels
- id: 'install-twine'
  name: python
  entrypoint: pip
  args:
  - install
  - --user
  - twine
  - keyrings.google-artifactregistry-auth
- id: 'export-wheels'
  waitFor: ['copy-wheels', 'install-twine']
  name: python
  entrypoint: python
  args:
  - '-m'
  - 'twine'
  - 'upload'
  - '--repository-url'
  - 'https://${_ARTIFACT_REGISTRY_REGION}-python.pkg.dev/$PROJECT_ID/torch-xla/'
  - '/wheels/*'
  volumes:
  - name: 'wheels'
    path: /wheels
- id: 'release-image'
  waitFor: ['build-wheels']
  name: 'gcr.io/kaniko-project/executor:debug'
  entrypoint: sh
  args:
  - -c
  - |
    /kaniko/executor \
      --dockerfile=docker/experimental/Dockerfile \
      --destination=${_IMAGE_URL} \
      $(cat /docker/flags.txt)
  timeout: 14400s
  volumes:
  - name: docker
    path: /docker
substitutions:
  _ARTIFACT_REGISTRY_REGION: us
  _IMAGE_URL: ${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/torch-xla-images/xla:${_RELEASE_VERSION}_${_PYTHON_VERSION}
  _BAZEL_JOBS: '16'
  _PYTHON_VERSION: '3.8'
  _RELEASE_VERSION: 'nightly'  # or rX.Y
  _CACHE: 'true'
  _CACHE_TTL: '18h'
  _BUILD_ARGS: tpuvm=1,cuda=0
options:
  machineType: E2_HIGHCPU_32
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
timeout: 24000s
