- name: Create /dist directory for exported wheels
  ansible.builtin.file:
    path: /dist
    state: directory
    mode: '0755'

- name: Build PyTorch/XLA CUDA Plugin
  ansible.builtin.command:
    cmd: pip wheel -w /dist plugins/cuda -v
    chdir: "{{ (src_root, 'pytorch/xla') | path_join }}"
  environment: "{{ env_vars }}"
  when: accelerator == "cuda"

- name: Find plugin *.whl files in pytorch/xla/dist
  ansible.builtin.find:
    path: "/dist"
    pattern: "torch_xla_cuda_plugin*.whl"
  register: plugin_wheels

- name: Install plugin wheels
  ansible.builtin.pip:
    name: "{{ plugin_wheels.files | map(attribute='path') }}"
    state: "forcereinstall"
