name: get-torch-commit
on:
  workflow_call:
    outputs:
      torch_commit:
        description: "torch commit to be used"
        value: ${{ jobs.get-commit.outputs.torch_commit }}

jobs:
  get-commit:
    runs-on: ubuntu-20.04
    outputs: 
      torch_commit: ${{ steps.get_torch_commit.outputs.torch_commit }}
    steps:
      # See https://github.com/actions/checkout/issues/1014#issuecomment-1906802802
      - name: Clean up workspace
        run: |
          ls -la
          rm -rvf ${GITHUB_WORKSPACE}/*
      - name: Checkout PyTorch Repo
        uses: actions/checkout@v4
        with:
          repository: pytorch/pytorch
          path: pytorch
          submodules: recursive
      - id: get_torch_commit
        name: Get torch commit
        run: |
          cd pytorch
          torch_commit=$(git rev-parse HEAD) 
          echo "torch_commit=$torch_commit" >> "$GITHUB_OUTPUT"
      
