name: Weekly Code Update PR
on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 9 * * 1'  # Each Monday 9:00AM (PDT time)

jobs:
  update_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Install sed
        run: sudo apt-get update && sudo apt-get install -y sed

      - name: Get JAX version for specified date
        run: |
          JAX_VERSION=$(curl -s https://storage.googleapis.com/jax-releases/jax_releases.json | jq -r '.[] | select(.released_on == "${{ env.CURRENT_DATE }}") | .version')
          if [ -z "$JAX_VERSION" ]; then
            echo "No JAX release found for ${{ env.CURRENT_DATE }}. Skipping update."
            exit 0
          fi
          echo "JAX_VERSION=$JAX_VERSION" >> $GITHUB_ENV

      - name: Update date in setup.py
        run: |
          sed -i "s/_date =.*/_date = '${{ env.CURRENT_DATE }}'/" ${FILE_PATH}
          sed -i "s/_jax_version =.*/_jax_version = f'${{ env.JAX_VERSION }}.dev${{ env.CURRENT_DATE }}'/" ${FILE_PATH}
          git add ${FILE_PATH}
          git commit -m "Weekly update setup.py to (${{ env.CURRENT_DATE }})"
          git push origin HEAD:weekly-update
        env:
          FILE_PATH: setup.py

      - name: Fetch HEAD commit from OpenXLA github repo
        run: |
          git remote add target https://github.com/openxla/xla.git
          git fetch target
          echo "HEAD_COMMIT=$(git rev-parse target/main)" >> $GITHUB_ENV

      - name: Update OpenXLA commit in WORKSPACE
        run: |
          sed -i "s/xla_hash =.*/xla_hash = '${{ env.GITHUB_ENV }}'/" ${FILE_PATH}
          git add ${FILE_PATH}
          git commit -m "Weekly update WORKSPACE with (${{ env.GITHUB_ENV }})"
          git push origin HEAD:weekly-update
        env:
          FILE_PATH: WORKSPACE

      - name: Create Pull Request
        uses: actions/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: weekly-update
          base: main
          title: "Weekly Code Update - ${{ env.CURRENT_DATE }}"
          body: "This PR contains the weekly OpenXLA-pin update at commit: (HEAD commit: ${{ env.HEAD_COMMIT }}), with libtpu version at ${{ env.CURRENT_DATE }}."


